### ISSUE TITLE
[ETS2 Promods] Tiles Generated v1.XX

### ISSUE THREAD

**Issue by krussedull** [TwinDragon/SCS_Map_Tiles#1]
hello how to get this map to work ?

**Comment by TwinDragon** [comment]
If you're wishing to self-host the map tiles and not use the GitHub in the Dashboard settings, you can follow [this writeup](https://github.com/JAGFx/ets2-dashboard-skin/blob/master/doc/MAP.md#self-hosting) on how to do so.
